export const skills = [
  "React",
  "React-Redux",
  "React-Saga",
  "React-Router",
  "React-Hooks",
  "Axios",
  "JavaScript",
  "HTML",
  "CSS",
  "Webpack",
  "Teamwork",
  "Git",
  "Github & Pull Requests",
  "Styled-components",
  "Markdown",
  "Visual-Studio-Code",
  "BEM-convention",
  "Grid & Flexbox",
  "Trello",
];

export const nextSkills = [
  "TypeScript",
  "Tests",
  "Java",
  "Sql",
  "Better design",
  "Write cleaner code",
];
